### ISSUE TITLE
Linux build error - ghc: panic!

### ISSUE THREAD

**Issue by achindra** [microsoft/bond#1187] opened 2023-04-28 14:47 UTC
Freshly enlisted repository on Linux (WSL)

```
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

> ghc: panic! (the 'impossible' happened)
>   (GHC version 8.6.5 for x86_64-unknown-linux):
>         Prelude.chr: bad argument: 2634022915

**cmake -B build -S .**
```
cmake -B build -S .
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.18", minimum required is "2.7")
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "2.7")
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.58.0") found components: chrono date_time thread system missing components: unit_test_framework python
-- Boost Python Library:
-- Stack found at /usr/local/bin/stack. Version 2.9.3, Git revision 6cf638947a863f49857f9cfbf72a38a48b183e7e x86_64 hpack-0.35.1
-- Configuring done (35.6s)
-- Generating done (0.5s)
-- Build files have been written to: /home/user/source/rpc/bond/build
</details>
```

**cmake --build ./build/**
```
cmake --build ./build/
[  9%] Generating build/gbc/gbc
/home/user/source/rpc/bond/compiler/bond.cabal was modified manually. Ignoring /home/user/source/rpc/bond/compiler/package.yaml in favor of the Cabal file.
If you want to use the package.yaml file instead of the Cabal file,
then please delete the Cabal file.
ghc: panic! (the 'impossible' happened)
  (GHC version 8.6.5 for x86_64-unknown-linux):
        Prelude.chr: bad argument: 2634022915

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug


Error: [S-6374]
       While building simple Setup.hs (scroll up to its section to see the error) using:
       /usr/bin/ghc-8.6.5 -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-2.4.0.1 /home/user/.stack/setup-exe-src/setup-SvXsv1f_.hs /home/user/.stack/setup-exe-src/setup-shim-SvXsv1f_.hs -o /home/user/.stack/setup-exe-cache/x86_64-linux/tmp-Cabal-simple_SvXsv1f__2.4.0.1_ghc-8.6.5
       Process exited with code: ExitFailure 1
CMake Error at stack_build.cmake:30 (message):
  build failed - scroll up for its output


make[2]: *** [compiler/CMakeFiles/gbc.dir/build.make:103: compiler/build/gbc/gbc] Error 1
make[1]: *** [CMakeFiles/Makefile2:927: compiler/CMakeFiles/gbc.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by bhardwajs** [comment] 2023-04-29 19:19
@achindra - The error message suggests this is a ghc bug. Would you mind reporting at: http://www.haskell.org/ghc/reportabug

**Comment by achindra** [comment] 2023-04-30 04:16
@bhardwajs, I opened a bug for [GHC](https://gitlab.haskell.org/ghc/ghc/-/issues/23325), however I am concerned how is Linux build passing in the bond pipeline.

**Comment by sheaf** [comment] 2023-05-02 15:36
This is caused by stale interface files; it's a bug in stack's recompilation checking.

**Comment by chwarr** [comment] 2023-05-10 20:36
Since this appears to be a bug in stack and not Bond, I'm going to close this issue.

**Closed by chwarr** 2023-05-10 20:36 UTC
