### ISSUE TITLE
Can't deserialize a bonded<T> containing a non-serilalized instance of T?

### ISSUE THREAD

**Issue by chmcclin** [Microsoft/bond#155] opened 2016-04-16 05:25 UTC
Hi,  I see a very clear comment regarding the deserialization of a bonded<T> containing a non-serialized instance of T, and an assert in protocol_visitors.h, but I'm a bit confused as to why I can't do this in the C++ library.  Around Line 121:
```
  121     bool operator()(ValueReader& value) const
  122     {
  123         // "De-serializing" bonded<T> containing a non-serialized instance of T
  124         BOOST_VERIFY(value.pointer == NULL);
  125         return false;
  126     }
```

I was playing with some simple attempts at using bonded<T> for polymorphic structures, but skipping the serialization.  Even igoring my polymorphic motifvations, a very simple (but contrived) example looks like:
```
Circle c;
c.radius = 2;

bonded<Circle> bc(c);
Circle c2;
bc.Deserialize(c2); // Fails with the assert form line 124 earlier in this question.
```
Is there a reason this isn't supported or am I doing something incorrectly?

My motivation for doing this is a staged approach at getting bond into my code base - initially I want to eal with the class structures internally until I can actually switch over to getting raw data from the supported data streams.

Thanks,
-Charles

**Comment by chadwalters** [comment] 2016-04-19 23:46
The Deserialize transform in C++ currently only works from serialized payloads by design; that was the anticipated primary use case. I agree that the docs don't make this clear. It does work with object instances in C# but largely because the implementation came along for free. In theory the C++ implementation could be extended to work with object instances. It might not even be that difficult -- although we'd have to look at the impact on compile time and object file sizes.

**Comment by chwarr** [comment] 2016-06-13 18:41
I'm going to close this issue now. Please feel free to re-open if there's anything more.

**Closed by chwarr** 2016-06-13 18:41 UTC
Labels: question

**Comment by drynzel** [comment] 2016-07-30 01:42
If de-serializing bonded<T> containing a non-serialized instance of T is not available how can I get its value?

**Comment by chwarr** [comment] 2016-08-05 21:27
@drynzel, you have two options I can think of off the top of my head:

* Don't wrap the structure in a `bonded<T>` in the first place. Just pass a `T` around.
* Serialize the `bonded<T>` then deserialize to a `T`.

If you would like to continue this discussion further, please start [a new issue](https://github.com/Microsoft/bond/issues/new).
