### ISSUE TITLE
Allow Bond.Attribute on enum fields

### ISSUE THREAD

**Issue by sahassansondos** [microsoft/bond#1070] opened 2020-09-10 02:09 UTC
can define something like
enum Results
{
        [Bond.Attribute("pass","true")]
        pass =0,
        [Bond.Attribute("pass","false")]
        retry =1,
}

**Comment by chwarr** [comment] 2020-09-10 19:36
This appears to be a duplicate of https://github.com/microsoft/bond/issues/138, "Add support for Bond attributes on enum values". If you are interested in contributing this functionality, please take a look at that issue and write up a design proposal.

Thanks.

**Closed by chwarr** 2020-09-10 19:36 UTC
Labels: duplicate, enhancement
