### ISSUE TITLE
Primitive types/bonded<Primitive> cannot be serialized

### ISSUE THREAD

**Issue by aschmahmann** [microsoft/bond#428] opened 2017-04-26 05:26 UTC
Starting with the most obvious case: The deserializer for System.String cannot even be created.

The following C# code throws an error.

```C#
new Deserializer<CompactBinaryReader<InputBuffer>>(typeof(String));
```

The error is `'System.String' does not have a default constructor`.

This appears to be another issue related to the deserializer looking to use the default constructor to get default values to use. While this methodology also causes issues with interfaces and abstract base classes (#263) and similarly reliance on default constructors is one of the reasons that the issues in #415 showed up, this particular instance is likely fixable with just having an exception for String (and other "primitive" Bond types).

Aside from the error thrown on creating the deserializer, the corresponding serializer returns 0 instead of an error or the correct answer (e.g. the serialized string). This appears to be a similar issue to #151 and is true for other "primitive" types such as int (however, the deserializers for int, List<T>, etc. don't throw an error since they do have a default constructor). This issue further exists for Bonded<T>, where T is a "primitive" Bond type.

If this is not clear, please let me know and I can clarify with some examples.

**Comment by chwarr** [comment] 2017-04-26 17:23
The root here is that none of `string`, `int`, `bonded<SomeBondType`, `List<int>` are types that can be serialized via a Bond Serializer. Bond Serializers work on Bond structs (annotated with the `[Bond.Schema]` attribute) and not on individual values.

There's an [existing, yet unfixed, issue](https://github.com/Microsoft/bond/issues/80) to emit a better error message in this case, pointing at the fact that a serializer can only be created for a class/struct annotated with `[Bond.Schema]`.

Going to close as a duplicate of that. Let me know if I've misunderstood.

**Comment by aschmahmann** [comment] 2017-04-26 18:37
I'm not really sure why this just a documentation/exception reporting error like #80 and #151 are. Why should this be invalid:

bug.bond
```
struct BondedContainer<T> {
      0: bonded<T> f1;
}

struct RegularContainer<T>{
      0: T f1;
}
```

bug.cs
```C#
//Everything looks fine, but if you serialize it is incorrect and you cannot deserialize f1 to get the data.
var bc = new BondedContainer<String>() { f1 = new Bonded<String>("This is a test") };

//This however is valid, and will allow serialization and deserialization just fine.
var bcWrapped = new BondedContainer<RegularContainer<String>>() { f1 = new Bonded<RegularContainer<String>>(new RegularContainer<String>() { f1="This is a test" }) };
```

Maybe the Bond team has decided that only crazy people would even want to use Bond to serialize/deserialize a primitive type directly such as the creator of #147. While I disagree with that assessment I understand that in many cases users will not need to work directly with non-Struct classes. **However**, the fact that I can't put a "primitive" bond type into a bonded<T> really is problematic.

To illustrate this imagine that I have some struct `S<T>` that contains structs that container other structs that somewhere down the line contains a `bonded<T>`. My current options are:

1. Warn users in documentation (since without writing a plugin there is no compile time warning) that some types of `S<T>` are invalid like `int`, `string` and `List<Y>` (for any Y)
2. Replace all instances `bonded<T>` with a custom `bondedWrapper<T>` and use properties to try and make this look similar. This is where `bondedWrapper<T>` looks like:
```
struct Wrapper<T>{
      0: T f1;
}

struct BondedWrapper<T> {
      0: bonded<Wrapper<T>> f1;
}
```

The fact that my next step is likely going to be to replace all instances of `bonded<T>` with a custom `bondedWrapper<T>` (at least when `T` is generic) indicates to me that something is wrong with `bonded<T>`. If you would like to continue describing #147 and the equivalents as "documentation errors" that I can sort of understand, but allowing `bonded<T>` to have this flaw I think is a real problem.

Let me know if there's something I've missed or if you have a better solution for dealing with my  `bonded<T>` issues.

**Comment by chwarr** [comment] 2017-04-26 23:02
I follow better now. Thanks for your comprehensive and detailed issue submissions. They help us understand how the library is being used and, perhaps more importantly, failing to be used.

You've identified a design flaw in the interaction between generics and `bonded<T>`.  The `T` in `bonded<T>` today must be a struct, but the `T` in a generic is unconstrained (or is constrained to be a value but that doesn't help here).

The assumption that serialization/deserialization begins with a struct is fairly deeply baked into the encoding protocols, the current concept of `bonded`, and the implementations across the languages.

So, simply relaxing serialization/bonded to work for any Bond type is something that needs to be done deliberately: what are the ramifications on the Bond type system? the encoding protocols? the APIs? existing serialized data? does stuffing everything in a [`bond.Box<T>`](https://github.com/Microsoft/bond/blob/f98e4403e3af74168e9e8361039f866a6e1e7b80/idl/bond/core/bond.bond#L127-L131) just work?

Alternatively, plugging the hole that allows non-struct types in `bonded<T>` would make the current implementation match our expected behavior, but may be artificially limiting.

I've opened a few other issues, mostly to make the current implementation fail fast and fail hard, but without closing the door on future improvements:

1. When running gbc on a .bond file, a field like `0: bonded<int32> SomeFieldName` will fail to compile with the error "unexpected reserved word 'int32', expecting user defined struct". However, when using generics, the compiler allows eventual creation of `bonded<string>`. gbc could detect many cases of this and reject them. Issue #430 captures this.
1. That the `T` in `bonded<T>` must be a struct is explicitly mentioned in the [gbc documentation](https://microsoft.github.io/bond/manual/compiler.html#struct-definition), but not really anywhere else. There should be more general documentation about how the Bond type system works, and issue #115 captures both of these deficiencies.
1. There's currently a lack of compile-time type safety in the C# implementation and the error messages don't help figure out what went wrong. I think they should be explicit and say things like "Type Foo cannot be serialized because it does not have a Bond schema. The [Bond.Schema] and [Bond.Id] attributes can be used to give it a Bond schema." The bug [where attempting to serialize a list produces garbage instead of a runtime exception](https://github.com/Microsoft/bond/issues/151) is a particularly bad manifestation of this problem.
1. The C# APIs make heavy use of unconstrained generic type parameters, resulting in a lack of compile-time type safety. Issue #429 captures this. This is a hard item to fix, as it needs to be done in a minimally breaking way, while still providing enough benefit to justify being done.

**Comment by chwarr** [comment] 2021-04-26 17:41
I believe there are individual issues open for the improvements discussed in this question. I'm going to close this issue for now. Feel free to re-open this issue with additional details if I've missed something. Thanks.

**Closed by chwarr** 2021-04-26 17:41 UTC
Labels: question
