### ISSUE TITLE
Bond in .NET 6 console app fails to load the assembly  

### ISSUE THREAD

**Issue by BRUT4LxD** [microsoft/bond#1144] opened 2022-04-15 23:13 UTC
Tried to compile this code in both .NET 5 and .NET 6 console applications: 

```
private static void Main(string[] args)
{
    var src = new A
    {
        Name = "FooBar",
        Records = { 3.14, 6.28 }
    };

    var output = new OutputBuffer();
    var writer = new CompactBinaryWriter<OutputBuffer>(output);

    // The first calls to Serialize.To and Deserialize<T>.From can take
    // a relatively long time because they generate the de/serializer
    // for a given type and protocol.
    Serialize.To(writer, src);

    Console.WriteLine(output.Data);

    var input = new InputBuffer(output.Data);
    var reader = new CompactBinaryReader<InputBuffer>(input);

    var dst = Deserialize<A>.From(reader);

    Console.WriteLine(dst.Name);
    Console.WriteLine(dst.Records.Count);
}
```

For .NET 5 I'm having expected result. For .NET 6 I'm have: 
`System.IO.FileNotFoundException: 'Could not load file or assembly 'Bond, Version=10.0.0.100, Culture=neutral, PublicKeyToken=87e9ead25a117286'. The system cannot find the file specified.'`

**Comment by chwarr** [comment] 2022-04-18 20:56
Hmmm... I'm not able to reproduce this problem. Do you have Bond.dll in the output directory of your proejct? Are you referencing--perhaps transitively--the Bond.Core.CSharp package? If there's no reference to the Bond.Core.CSharp package anywhere in the dependency graph, I could see this error occurring, especially if the Bond.Compiler.CSharp package is being used. The fix is to add a package reference to your .csproj that invokes the serialization code.

```xml
<ItemGroup>
  <PackageReference Include="Bond.Core.CSharp" Version="10.0.0" />
</ItemGroup>
```

The C# Bond documentation has [more details about what is in each of the NuGet packages](https://microsoft.github.io/bond/manual/bond_cs.html#nuget-packages).

----------

Here's the code I used to try to reproduce this.

dnc.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0;net6.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bond.Core.CSharp" Version="10.0.0" />
  </ItemGroup>

</Project>
```

Program.cs

```csharp
namespace dnc
{
    using System;

    using Bond;
    using Bond.IO.Safe;
    using Bond.Protocols;

    [Bond.Schema]
    class Foo
    {
        [Bond.Id(0)]
        public string Value { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var f = new Foo { Value = "testing .NET 6" };

            var output = new OutputBuffer();
            var writer = new CompactBinaryWriter<OutputBuffer>(output);

            Serialize.To(writer, f);

            Console.WriteLine($"CB payload length: {output.Data.Count}");

            var input = new InputBuffer(output.Data);
            var reader = new CompactBinaryReader<InputBuffer>(input);

            var dst = Deserialize<Foo>.From(reader);

            Console.WriteLine(dst.Value);
        }
    }
}
```

Both `dotnet run --framework net5.0` and `dotnet run --framework net6.0` print the same things for me:

```plain
CB payload length: 17
testing .NET 6
```

`dotnet --info` output:

```plain
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

... elided ...
```

**Comment by BRUT4LxD** [comment] 2022-04-27 23:12
Ok. I will add a bit more details. 
I created 2 projects - `.net5` and `.net6`. The latter was created with 1 line `Program.cs` (`Console.WriteLine("HelloWorld")`). I added the `Main` function where I wrote the code above. The `.net5` project had namespace, class and `Main` method from the beginning. At this point I did the same for both projects: 
1. I created the `.bond` file
2. I ran the command `gbc c# ...` in Visual Studio 2022 PS terminal (Red squiggly lines indicating the error for the missing class went off the screen)
3. I launched the project from Visual Studio 2022

After that .NET 5 is printing the correct result and .NET6 fails with error `System.IO.FileNotFoundException: 'Could not load file or assembly 'Bond, Version=10.0.0.100, Culture=neutral, PublicKeyToken=87e9ead25a117286'. The system cannot find the file specified.'`

**Comment by chwarr** [comment] 2022-04-28 00:42
Thanks for the extra details. I think I understand what's going on now.

Try adding this block to your .csproj. This will automatically generate .cs files from .bond files at build time and include the right assemblies for runtime, like Bond.dll. If you see the error about missing classes when you first launch Visual Studio, try building the project once. That will run gbc which should then make the generated code visible to Visual Studio.

```xml
  <ItemGroup>
    <PackageReference Include="Bond.CSharp" Version="10.0.0" />
  </ItemGroup>
```

If you want to run codegen manually like you did in step 2, you only need `<PackageReference Include="Bond.Core.CSharp" Version="10.0.0" />`. You will have to run `gbc` yourself each time you change the .bond files, which is why I suggest `<PackageReference Include="Bond.CSharp" Version="10.0.0" />` instead.

For some more details, see the [documentation about what's in each of Bond's NuGet packages](https://microsoft.github.io/bond/manual/bond_cs.html#nuget-packages).

**Comment by chwarr** [comment] 2022-05-12 02:00
I think this has been answered, so I'm going to close this issue. If not, please feel free to re-open with your current findings. Thanks.

**Closed by chwarr** 2022-05-12 02:00 UTC
Labels: question
