### ISSUE TITLE
.NET AOT friendly version of Bond

### ISSUE THREAD

**Issue by mjsabby** [microsoft/bond#1037] opened 2020-05-12 11:10 UTC
Bond uses System.Linq.Expressions to do runtime codegeneration or interpreting depending on if the .NET runtime it is running on supports codegen or not.

Internally at Microsoft there exists a toolchain of Bond that does not require runtime code-generation or falling back to the interpreter. It just generates regular C# files as part of the compilation.

For programs that want fast startup and are targetting .NET precompilation technology like ReadyToRun, CoreRT it should be a major boost because all the code will be available for precompilation.

**Comment by chwarr** [comment] 2020-05-12 18:35
Looks like a duplicate of https://github.com/microsoft/bond/issues/56

**Closed** 2020-05-12 18:36 UTC
Labels: duplicate, enhancement
