### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [Microsoft/bond#5] opened 2015-01-11 12:38 UTC
Some parameters (like "[${CMAKE_CFG_INTDIR}](https://github.com/Microsoft/bond/blob/222e20fd00fd49ef0189b3a6369e8cac433d816c/CMakeLists.txt#L23)" and "[${BOND_INCLUDE}/bond/core/bond.bond](https://github.com/Microsoft/bond/blob/222e20fd00fd49ef0189b3a6369e8cac433d816c/cpp/CMakeLists.txt#L1)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by sapek** [comment] 2015-01-14 23:54
I'm not able to reproduce the issue, probably not because there isn't one, but because other components fails with paths that would lead to the problem. 

On Windows git fails to clone repo with submodules into directory with a semicolon in it. Path with spaces are fine and the Bond project build w/o problems.

On Mac/Linux cmake completely doesn't work with paths that have semicolon or space. If binary directory has those characters cmake fails in `Modules/CMakeDetermineCompilerId.cmake:90`, before it even starts processing any Bond specified paths. If only source directory has those characters then cmake fails to include modules, even when path added to `CMAKE_MODULE_PATH` are quoted.

W/o a specific repro I'm going to close this issue. In theory could just proactively quote things but given that cmake has a lot of idiosyncrasies I don't want to be making "fixes" I can't verify.

If you encounter a specific problem please reopen with repo instructions. Thanks.

**Closed by sapek** 2015-01-14 23:54 UTC
